### PR TITLE
TeoDor

### PR DESCRIPTION
**Pull request by Tudor1301**

### CODE REVIEW

**Review by sjasot — APPROVED** [review]
good job

**Review by Mboonetech — APPROVED** [review]

**Review by DelibasicIvan — APPROVED** [review]

**Review by sjasot — APPROVED** [review]
G

**Comment by sjasot** [comment]
ok

**Review by sjasot — APPROVED** [review]
reviewed

**Review by sjasot — APPROVED** [review]
checked all of them

**Review by DelibasicIvan — APPROVED** [review]

**Review by DelibasicIvan — APPROVED** [review]

**Review by DelibasicIvan — APPROVED** [review]

**Review by DelibasicIvan — APPROVED** [review]

**Pull request closed without merging**
